# Generated by Django 4.2.13 on 2024-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
                ("bounding_box_x", models.FloatField()),
                ("bounding_box_y", models.FloatField()),
                ("bounding_box_width", models.FloatField()),
                ("bounding_box_height", models.FloatField()),
                ("score", models.FloatField()),
                ("mask", models.JSONField()),
            ],
        ),
    ]
