# Generated by Django 4.2.13 on 2024-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionresult",
            name="image_name",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="mask",
        ),
        migrations.AddField(
            model_name="detectionresult",
            name="mask_data",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="detectionresult",
            name="bounding_box_height",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="detectionresult",
            name="bounding_box_width",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="detectionresult",
            name="bounding_box_x",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="detectionresult",
            name="bounding_box_y",
            field=models.IntegerField(),
        ),
    ]
