# Generated by Django 4.2.13 on 2024-08-20 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_remove_detectionresult_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
