# Generated by Django 4.2.13 on 2024-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0004_detectionresult_id_predictions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="image_base64",
            field=models.TextField(blank=True, default=""),
        ),
    ]
